// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
        app:{
            head:{
                link:[
                    {
                        rel:"stylesheet", href:"/assets/css/main.css?v=5.6"
                    },
                    {
                        rel:"shortcut icon", type:"image/x-icon", href:"/assets/imgs/theme/favicon.svg" 

                    },
                    {
                        rel:"stylesheet",
                        href:"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" 
                    }
                ],
                script:[
                    {
                        src:"/assets/js/vendor/modernizr-3.6.0.min.js"                    
                    },
                    {
                        src:"/assets/js/vendor/jquery-3.6.0.min.js"                  
                    },
                    {
                        src:"/assets/js/vendors/select2.min.js"
                    },
                    {
                        src:"/assets/js/vendor/jquery-migrate-3.3.0.min.js"                    
                    },
                    {
                        src:"/assets/js/vendor/bootstrap.bundle.min.js"                    
                    },
                    {
                        src:"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js",
                        defer: true                    
                    },
                    {
                        src:"/assets/js/plugins/jquery.syotimer.min.js"                    
                    },
                    {
                        src:"/assets/js/plugins/waypoints.js"                    
                    },
                    {
                        src:"/assets/js/plugins/wow.js"
                    },
                    {
                        src:"/assets/js/plugins/perfect-scrollbar.js"
                    },
                    {
                        src:"/assets/js/plugins/magnific-popup.js"
                    },
                    {
                        src:"/assets/js/plugins/select2.min.js"
                    },
                    {
                        src:"/assets/js/plugins/counterup.js"
                    },
                    {
                        src:"/assets/js/plugins/jquery.countdown.min.js"
                    },
                    {
                        src:"/assets/js/plugins/images-loaded.js"
                    },
                    {
                        src:"/assets/js/plugins/isotope.js"
                    },
                    {
                        src:"/assets/js/plugins/scrollup.js"
                    },
                    {
                        src:"/assets/js/plugins/jquery.vticker-min.js"
                    },
                    {
                        src:"/assets/js/plugins/jquery.theia.sticky.js"
                    },
                    {
                        src:"/assets/js/plugins/jquery.elevatezoom.js"
                    },
                    {
                        src:"/assets/js/main.js?v=5.6"
                    }
                ]
            }
        },
            modules: [
                ['@pinia/nuxt', {disableVuex: true}],
                '@pinia-plugin-persistedstate/nuxt'
    ]
})
